package com.myhome.entity;

import java.sql.Date;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.myhome.utils.DateUtil;

/**
 * 老师 TTeacher generated by hbm2java
 */
public class Teacher extends AbstractEntity {

	private String name;// 姓名
	private String img;
	private String thumbnailImg;// 照片(缩略图)
	private Boolean male = true;// 性别
	private Date birthday;// 生日
	/**
	 * 
	 * 所属星座，例如：狮子座
	 * 
	 */
	private String constellation;

	/**
	 * 
	 * 生肖
	 * 
	 */
	private String zodiac;
	private String workUnit;// 工作单位
	private String mobile;// 手机号
	private String celtyl;// 教师职工证
	private String nation;// 民族
	private String thumbnailCeltyl;
	
	private Integer age;
	@JsonIgnore
//	@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
	private Region region;// 城市
	private User user;// 用户id

	private String token;//验证手机端上传是否成功
	
	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Date getBirthday() {
		return birthday==null?null:birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public Region getRegion() {
		return region;
	}

	public void setRegion(Region region) {
		this.region = region;
	}

	public String getWorkUnit() {
		return workUnit;
	}

	public void setWorkUnit(String workUnit) {
		this.workUnit = workUnit;
	}

	public String getMobile() {
		return mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getCeltyl() {
		return celtyl;
	}

	public void setCeltyl(String celtyl) {
		this.celtyl = celtyl;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public String getNation() {
		return nation;
	}

	public void setNation(String nation) {
		this.nation = nation;
	}

	

	public String getThumbnailCeltyl() {
		return thumbnailCeltyl;
	}

	public void setThumbnailCeltyl(String thumbnailCeltyl) {
		this.thumbnailCeltyl = thumbnailCeltyl;
	}

	public Boolean getMale() {
		return male;
	}

	public void setMale(Boolean male) {
		this.male = male;
	}

	public Integer getAge() {
		if(this.getBirthday()!=null){
			return  DateUtil.getage(this.getBirthday());
		}else{
			return age;
		}
		
	}
	public void setAge(Integer age) {
		this.age = age;
	}

	public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}

	public String getThumbnailImg() {
		return thumbnailImg;
	}

	public void setThumbnailImg(String thumbnailImg) {
		this.thumbnailImg = thumbnailImg;
	}

	public String getToken() {
		return token;
	}

	public void setToken(String token) {
		this.token = token;
	}

	public String getConstellation() {
		return constellation;
	}

	public void setConstellation(String constellation) {
		this.constellation = constellation;
	}

	public String getZodiac() {
		return zodiac;
	}

	public void setZodiac(String zodiac) {
		this.zodiac = zodiac;
	}

	

}
