  -- gwb 051008
  ALTER TABLE  t_user_info   
   ADD COLUMN img VARCHAR(200) NULL  COMMENT '用户头像' ,
   ADD COLUMN origin_img VARCHAR(200) NULL  COMMENT '用户头像原图' ,
   ADD COLUMN account DOUBLE(10,2) NULL  COMMENT '账户金额',
   ADD COLUMN profession VARCHAR(64) NULL  COMMENT '职业' ,
   ADD COLUMN mobile VARCHAR(16) NULL  COMMENT '联系方式' ,
   ADD COLUMN nick_name VARCHAR(32) NULL  COMMENT '昵称' ,
   ADD COLUMN token VARCHAR(32) NULL  COMMENT '验证手机端上传是否成功' ,
   ADD COLUMN balance DOUBLE(10,2) NULL 	COMMENT '账户余额',
   ADD COLUMN TYPE INT(2) DEFAULT 1 NULL  COMMENT '角色类型 1普通用（默认）,2画家，3受捐者，4老师，5赞助商,6同时是画家和受捐者' ;

-- gwb 20151019
ALTER TABLE t_artist_info  
  ADD COLUMN cartoon VARBINARY(200) NULL  COMMENT '最喜欢的动漫' ;

-- 
ALTER TABLE t_works
MODIFY COLUMN created_datetime  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;



DROP TABLE IF EXISTS t_want_buy_house;

CREATE TABLE t_want_buy_house (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  invalid TINYINT(4) DEFAULT '0',
  status INT(11) DEFAULT '1',
  created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_datetime DATETIME DEFAULT NULL,
  order_tag INT(11) DEFAULT '1',
  name VARCHAR(64) DEFAULT NULL COMMENT '您希望购房的楼盘',
  house_type INT(11) DEFAULT NULL COMMENT '户型',
  purchase_time DATE DEFAULT NULL COMMENT '预购时间',
  purchasing_budget INT(10) DEFAULT NULL COMMENT '购买预算',
  house_for_sale INT(1) DEFAULT NULL COMMENT '你是否有房屋需要出售1是，0否',
  region_id BIGINT(20) DEFAULT NULL,
  area INT(11) DEFAULT NULL COMMENT '购房面积',
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='调查问卷_我要买房';


DROP TABLE IF EXISTS t_want_to_decorate;

CREATE TABLE t_want_to_decorate (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  invalid TINYINT(4) DEFAULT '0',
  status INT(11) DEFAULT '1',
  created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_datetime DATETIME DEFAULT NULL,
  order_tag INT(11) DEFAULT '1',
  name VARCHAR(64) DEFAULT NULL COMMENT '楼盘名称',
  area INT(3) DEFAULT NULL COMMENT '面积',
  budget BIGINT(10) DEFAULT NULL COMMENT '装修预算',
  wish VARCHAR(1000) DEFAULT NULL COMMENT '对未来家的想象和愿望',
  airbnb INT(1) DEFAULT NULL COMMENT '加入短租airbnb:1是，0否',
  house_for_sale INT(1) DEFAULT NULL COMMENT '房屋出售1是，0否',
  unit_price INT(6) DEFAULT NULL COMMENT '单价',
  region_id BIGINT(20) DEFAULT NULL COMMENT '你家所在的城市',
  date DATETIME DEFAULT NULL COMMENT '购房时间',
  user_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='调查问卷_我要装修';


DROP TABLE IF EXISTS t_generous_gifts;

CREATE TABLE t_generous_gifts (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  invalid TINYINT(4) DEFAULT '0',
  status INT(11) DEFAULT '1',
  created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_datetime DATETIME DEFAULT NULL,
  order_tag INT(11) DEFAULT '1',
  name VARCHAR(24) DEFAULT NULL COMMENT '姓名',
  mobile VARCHAR(16) DEFAULT NULL COMMENT '联系方式',
  region_id BIGINT(20) DEFAULT NULL COMMENT '城市',
  address VARCHAR(255) DEFAULT NULL COMMENT '详细地址',
  user_id BIGINT(200) DEFAULT NULL COMMENT '推荐者id',
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='调查问卷_丰厚的礼品';

DROP TABLE IF EXISTS t_help_children;

CREATE TABLE t_help_children (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  invalid TINYINT(4) DEFAULT '0',
  STATUS INT(11) DEFAULT '1',
  created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_datetime DATETIME DEFAULT NULL,
  order_tag INT(11) DEFAULT '1',
  name VARCHAR(32) DEFAULT NULL COMMENT '姓名',
  photograph VARCHAR(200) DEFAULT NULL COMMENT '照片',
  male TINYINT(1) DEFAULT NULL COMMENT '性别0女 1男',
  birthday DATE DEFAULT NULL COMMENT '生日',
  zodiac VARCHAR(16) DEFAULT NULL COMMENT '属相',
  constellation VARCHAR(16) DEFAULT NULL COMMENT '星座',
  nation VARCHAR(16) DEFAULT NULL COMMENT '名族/国家',
  origin VARCHAR(16) DEFAULT NULL COMMENT '籍贯',
  address VARCHAR(100) DEFAULT NULL COMMENT '通讯地址',
  id_code VARCHAR(32) DEFAULT NULL COMMENT '身份证号',
  parent_mobile VARCHAR(16) DEFAULT NULL COMMENT '联系方式',
  parnet_id_code VARCHAR(32) DEFAULT NULL COMMENT '家长省份证号',
  current_status VARCHAR(100) DEFAULT NULL COMMENT '目前状况',
  wish VARCHAR(200) DEFAULT NULL COMMENT '目前愿望',
  significative VARCHAR(200) DEFAULT NULL COMMENT '做过一件有意义的事',
  parent_name VARCHAR(16) DEFAULT NULL COMMENT '家长姓名',
  user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
  region_id BIGINT(20) DEFAULT NULL COMMENT '区域id',
  school VARCHAR(32) DEFAULT NULL,
  smallphotograph VARCHAR(200) DEFAULT NULL COMMENT '缩略图',
  dream_fund DOUBLE DEFAULT NULL COMMENT '梦想基金',
  age INT(2) DEFAULT NULL COMMENT '年龄',
  img VARCHAR(200) DEFAULT NULL,
  thumbnail_img VARCHAR(200) DEFAULT NULL,
  token VARCHAR(32) DEFAULT NULL COMMENT 'token',
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=92 DEFAULT CHARSET=utf8 COMMENT='受帮助的小朋友';


DROP TABLE IF EXISTS t_teacher;

CREATE TABLE t_teacher (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  invalid TINYINT(4) DEFAULT '0',
  STATUS INT(11) DEFAULT '1',
  created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_datetime DATETIME DEFAULT NULL,
  order_tag INT(11) DEFAULT '1',
  name VARCHAR(32) DEFAULT NULL COMMENT '姓名',
  male INT(1) DEFAULT NULL COMMENT '性别0女 1男',
  birthday DATE DEFAULT NULL COMMENT '生日',
  region_id BIGINT(20) DEFAULT NULL COMMENT '城市',
  work_unit VARCHAR(100) DEFAULT NULL COMMENT '工作单位',
  mobile VARCHAR(16) DEFAULT NULL COMMENT '联系方式',
  celtyl VARCHAR(200) DEFAULT NULL COMMENT '认证信息（教师资格证）图片',
  user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
  nation VARCHAR(20) DEFAULT NULL COMMENT '名族',
  thumbnail_celtyl VARCHAR(200) DEFAULT NULL COMMENT '认证信息缩略图',
  age INT(200) DEFAULT NULL COMMENT '年龄',
  img VARCHAR(200) DEFAULT NULL COMMENT '头像',
  thumbnail_img VARCHAR(200) DEFAULT NULL COMMENT '头像缩略图',
  token VARCHAR(32) DEFAULT NULL COMMENT '验证手机端上传是否成功',
  constellation VARCHAR(32) DEFAULT NULL COMMENT '星座',
  zodiac VARCHAR(32) DEFAULT NULL COMMENT '生肖',
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COMMENT='老师';

DROP TABLE IF EXISTS t_with_picture;

CREATE TABLE t_with_picture (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  invalid TINYINT(4) DEFAULT '0',
  status INT(11) DEFAULT '1',
  created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_datetime DATETIME DEFAULT NULL,
  order_tag INT(11) DEFAULT '1',
  path VARCHAR(200) DEFAULT NULL COMMENT '缩略图',
  origin_path VARCHAR(200) DEFAULT NULL COMMENT '原图',
  description VARCHAR(200) DEFAULT NULL,
  type INT(2) DEFAULT NULL COMMENT '类型：2 受捐助者生活照',
  user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
  token VARCHAR(32) DEFAULT NULL COMMENT '验证手机端上传是否成功',
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8 COMMENT='生活照';


DROP TABLE IF EXISTS t_sponsors;

CREATE TABLE t_sponsors (
  id BIGINT(20) NOT NULL AUTO_INCREMENT,
  invalid TINYINT(4) DEFAULT '0',
  STATUS INT(11) DEFAULT '1',
  created_datetime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  updated_datetime DATETIME DEFAULT NULL,
  order_tag INT(11) DEFAULT '1',
  logo VARCHAR(200) DEFAULT NULL COMMENT '公司logo',
  thumbnail_logo VARCHAR(200) DEFAULT NULL COMMENT 'logo缩略图',
  company_name VARCHAR(200) DEFAULT NULL COMMENT '公司名称',
  mobile VARCHAR(16) DEFAULT NULL COMMENT '联系方式',
  business_license VARCHAR(200) DEFAULT NULL COMMENT '营业执照图片',
  t_business_license VARCHAR(200) DEFAULT NULL COMMENT '营业执照图片缩略图',
  open_account VARCHAR(200) DEFAULT NULL COMMENT '开户许可证',
  tax_registration VARCHAR(200) DEFAULT NULL COMMENT '税务登记证',
  organization_code VARCHAR(200) DEFAULT NULL COMMENT '组织机构代码证',
  region_id VARCHAR(20) DEFAULT NULL COMMENT '公司所在城市',
  address VARCHAR(200) DEFAULT NULL COMMENT '通讯地址',
  user_id BIGINT(20) DEFAULT NULL COMMENT '用户id',
  certificate VARCHAR(200) DEFAULT NULL COMMENT '证书文件',
  SCertificate VARCHAR(200) DEFAULT NULL COMMENT '证书文件缩列图',
  certificate_type INT(1) DEFAULT NULL COMMENT '证书文件类型\r\n1 开户许可证\r\n2 税务登记证\r\n3 组织机构代码证',
  token VARCHAR(32) DEFAULT NULL COMMENT '验证手机端上传是否成功',
  PRIMARY KEY (id)
) ENGINE=INNODB AUTO_INCREMENT=25 DEFAULT CHARSET=utf8 COMMENT='赞助商';

-- lqf 201511 12
ALTER TABLE t_region  
  ADD COLUMN name_code VARBINARY(200) NULL  COMMENT '地区拼音名字' ;