-- 创建小画家日志
DROP TABLE IF EXISTS `t_log_artist_info`;
CREATE TABLE `t_log_artist_info` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `invalid` tinyint(4) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `created_datetime` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_datetime` timestamp NULL DEFAULT NULL,
  `order_tag` int(11) DEFAULT '1',
  `artist_id` bigint(20) DEFAULT NULL,
  `male` int(1) DEFAULT NULL,
  `birthday` date DEFAULT NULL,
  `region_id` bigint(20) DEFAULT NULL,
  `name` varchar(64) DEFAULT NULL,
  `nation` varchar(64) DEFAULT NULL,
  `constellation` varchar(200) DEFAULT NULL,
  `zodiac` varchar(200) DEFAULT NULL,
  `id_code` varchar(200) DEFAULT NULL,
  `parent_mobile` varchar(200) DEFAULT NULL,
  `school` varchar(200) DEFAULT NULL,
  `school_mobile` varchar(200) DEFAULT NULL,
  `instructor` varchar(200) DEFAULT NULL,
  `instructor_mobile` varchar(200) DEFAULT NULL,
  `teacher` varchar(200) DEFAULT NULL,
  `teacher_mobile` varchar(200) DEFAULT NULL,
  `img` varchar(200) DEFAULT NULL,
  `referrer_school` varchar(200) DEFAULT NULL COMMENT '推荐人学校',
  `referrer_mobile` varchar(16) DEFAULT NULL COMMENT '推荐人联系方式',
  `age` int(11) DEFAULT NULL,
  `user_id` bigint(20) DEFAULT NULL COMMENT '用户id',
  `orginimg` varchar(200) DEFAULT NULL COMMENT '原图路径',
  `origin` varchar(200) DEFAULT NULL COMMENT '籍贯',
  `cartoon` varchar(200) DEFAULT NULL COMMENT '喜欢的卡通形象',
  `token` varchar(32) DEFAULT NULL COMMENT '验证手机端上传是否成功',
  `alipay_account` varchar(32) DEFAULT NULL COMMENT '支付宝账户',
  `bank_account` varchar(32) DEFAULT NULL COMMENT '银行卡号',
  `bank_name` varchar(32) DEFAULT NULL COMMENT '银行名称',
  `account_name` varchar(32) DEFAULT NULL COMMENT '开户人姓名',
  `invitation_code` varchar(32) DEFAULT NULL COMMENT '开户人姓名',
  `training_institution` varchar(32) DEFAULT NULL COMMENT '培训机构',
  `weChat_account` varchar(32) DEFAULT NULL COMMENT '微信账户',
  `artistinfo_id` bigint(20) DEFAULT NULL COMMENT '小画家信息id',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8 COMMENT='画家明细表';